#server:
#  port: 9090
#spring:
#  application:
#    name: spring-rest-security
#  profiles:
#   active: default
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mapping
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          ddl-auto: create
#      show-sql: true
##spring.sql.init.mode: always
#spring:sql:init:data-locations: classpath:data.sql
#
#
#security:
# jwt:
#    secret-key: moses
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
