server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
   active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/mapping
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    spring.sql:init:mode: always
    spring.sql:init:data-locations: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
      show-sql: false
security:
  jwt:
    secret-key: moses

