-- INSERT INTO student(first_name, last_name, email) VALUES ('Mike', 'Smith', 'mike.smith@abc.com');
-- INSERT INTO student(first_name, last_name, email) VALUES ('Mile', 'Tyson', 'mike.tyson@abc.com');
-- INSERT INTO student(first_name, last_name, email) VALUES ('Melenda', 'Smith', 'Melenda.smith@abc.com');
-- INSERT INTO student(first_name, last_name, email) VALUES ('Black', 'Smith', 'black.smith@abc.com');
--
-- INSERT INTO car(make, model) VALUES ('Honda','SUV');